### PR TITLE
Player heal()

### PR DESCRIPTION
**Pull request by AleksKors**
### What has been done:
- **Added** a heal method to player

**Related issues:**
#39

### CODE REVIEW

**Comment by MidnightRocket** [comment]
Please describe the use cases for this change. Why not utilize the `IHealingEntity` interface?

**Comment by AleksKors** [comment]
> Please describe the use cases for this change. Why not utilize the `IHealingEntity` interface?

I understood `IHealingEntity` as only having a method for getting heal amount, and the player doesn't have a method to change health other than the `takeDamage()` method.

**Comment by MidnightRocket** [comment]
Ah okay I just got confused because the method was public. Hmm we should be doing a better job making methods private unless otherwise needed. 

Also I don't understand why the entityManager needs to passed in?

**Comment by AleksKors** [comment]
I removed ´entityManager´ as an parameter and changed some accessibility modifiers for some of the methods in the player class.

**Pull request merged**
